export class Example {
  public alerts: any[] | null;
  public archivable: boolean | null;
  public availableInLibrary: boolean | null;
  public copyable: boolean | null;
  public createdBy?: string | null;
  public createdDate?: Date | null;
  public criteria: string | null;
  public criteriaExpression: string | null;
  public dataChanged: boolean | null;
  public deletable: boolean | null;
  public description: string | null;
  public environment: string | null;
  public errMsg: string | null;
  public failureLogLabel: string | null;
  public id: string | null;
  public isNestedSuppressionRule: boolean | null;
  public lastUpdatedDate: string | null;
  public micro: number | null;
  public modifiedBy?: string | null;
  public modifiedDate?: Date | null;
  public name: string | null;
  public owner: string | null;
  public presentationOrder: number | null;
  public priorityOrder: number | null;
  public publishable: boolean | null;
  public renamable: boolean | null;
  public state: string | null;
  public status: string | null;
  public successLogLabel: string | null;
  public suppressionId: number | null;
  public suppressionVersion: string | null;
  public unarchivable: boolean | null;
  public updatable: boolean | null;
  public userFriendlyExpression: string | null;
  public version: number | null;
  public versionable: boolean | null;

  constructor() {
    this.alerts = [];
    this.archivable = true;
    this.availableInLibrary = true;
    this.copyable = false;
    this.criteria = null;
    this.criteriaExpression = null;
    this.dataChanged = false;
    this.deletable = true;
    this.description = null;
    this.environment = null;
    this.errMsg = null;
    this.failureLogLabel = null;
    this.id = null;
    this.isNestedSuppressionRule = false;
    this.lastUpdatedDate = null;
    this.micro = null;
    this.name = null;
    this.owner = null;
    this.presentationOrder = null;
    this.priorityOrder = null;
    this.publishable = true;
    this.renamable = true;
    this.state = null;
    this.status = 'DRAFT';
    this.successLogLabel = null;
    this.suppressionId = null;
    this.suppressionVersion = null;
    this.unarchivable = false;
    this.updatable = true;
    this.userFriendlyExpression = null;
    this.version = 1;
    this.versionable = true;
  }
}
