export const EXAMPLE_DATA: any[]= [
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR6078187D2283E166533",
    "name": "RECHARGED_TODAY",
    "description": "Identifies if the customer has done a recharge today",
    "successLogLabel": "Recharged Today",
    "failureLogLabel": "Not Recharged Today",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "7.0.28",
    "suppressionId": 938840,
    "micro": 28,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 1,
    "priorityOrder": 11,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR9881187D22B86719445",
    "name": "UNIVERSAL_CONTROL_GROUP",
    "description": "Is a member of the Universal Control Group",
    "successLogLabel": "In UCG",
    "failureLogLabel": "In UTG",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "4.0.18",
    "suppressionId": 938844,
    "micro": 18,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 2,
    "priorityOrder": 10,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR263187D23092A03732",
    "name": "NO_MARKETING_CONSENT",
    "description": "Have  not provided marketing consent for any channel",
    "successLogLabel": "No Marketing Consent",
    "failureLogLabel": "Marketing Consent",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "10.0.38",
    "suppressionId": 1947245,
    "micro": 38,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 3,
    "priorityOrder": 1,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR404218809690A806853",
    "name": "DND_CUSTOMER",
    "description": "Excludes customers on DND list",
    "successLogLabel": "DND Customer",
    "failureLogLabel": "Not DND Customer",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "8.0.35",
    "suppressionId": 952276,
    "micro": 35,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 5,
    "priorityOrder": 8,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR216418829493A972887",
    "name": "NOT_ACTIVE",
    "description": "Inactive user",
    "successLogLabel": "Inactive",
    "failureLogLabel": "Active",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "9.0.37",
    "suppressionId": 401816,
    "micro": 37,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 7,
    "priorityOrder": 20,
    "alerts": [
      null
    ],
    "state": "STOPPING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR22381886B42D8F99620",
    "name": "TEST",
    "description": "Test Case",
    "successLogLabel": "Test",
    "failureLogLabel": "N Test",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "4.0.17",
    "suppressionId": 401817,
    "micro": 17,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 14,
    "priorityOrder": 19,
    "alerts": [
      null
    ],
    "state": "STOPPING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR8743188757F02978555",
    "name": "PACK_PURCHASE_TODAY",
    "description": "Excludes customers that purchased a pack today",
    "successLogLabel": "Pack Purchased Today",
    "failureLogLabel": "No Pack Purchased Today",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "2.0.16",
    "suppressionId": 401818,
    "micro": 16,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 15,
    "priorityOrder": 18,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR29771892376DBD0179",
    "name": "OPEN_RECHARGE_CAMPAIGN",
    "description": "Is in Recharge Campaign",
    "successLogLabel": "In Recharge Campaign",
    "failureLogLabel": "Not in Recharge Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "1.0.4",
    "suppressionId": 516440,
    "micro": 4,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 24,
    "priorityOrder": 15,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR5294189237D9C3C3267",
    "name": "OPEN_REVENUE_CAMPAIGN",
    "description": "Is in Revenue Campaign",
    "successLogLabel": "In Revenue Campaign",
    "failureLogLabel": "Not in Revenue Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "1.0.4",
    "suppressionId": 516439,
    "micro": 4,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 25,
    "priorityOrder": 16,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR58031892515E7EF5109",
    "name": "OPEN_PACK_CAMPAIGN",
    "description": "Is in Pack Campaign",
    "successLogLabel": "In Pack Campaign",
    "failureLogLabel": "Not in Pack Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "1.0.4",
    "suppressionId": 538306,
    "micro": 4,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 27,
    "priorityOrder": 14,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR64511898C259A296710",
    "name": "TEST_DND_CUSTOMER_1",
    "description": "Excludes customers on DND list",
    "successLogLabel": "DND Customer",
    "failureLogLabel": "Not DND Customer",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "1.0.3",
    "suppressionId": 645855,
    "micro": 3,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 30,
    "priorityOrder": 13,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR972818B60DFC3539480",
    "name": "NO_EMAIL_CONSENT",
    "description": "Have not provided marketing consent via Email",
    "successLogLabel": "No Email Consent",
    "failureLogLabel": "Email Consent",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "1.0.3",
    "suppressionId": 1041318,
    "micro": 3,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 34,
    "priorityOrder": 7,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
  {
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR184118BEAE2F8DC5364",
    "name": "OPEN_CHURN_CAMPAIGN",
    "description": "Is in Churn Suppression Campaign",
    "successLogLabel": "In Churn Campaign",
    "failureLogLabel": "Not in Churn Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "2.0.9",
    "suppressionId": 1947244,
    "micro": 9,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 35,
    "priorityOrder": 2,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },{
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR842918C61A8C2833661",
    "name": "OPEN_CHURN_CAMPAIGN",
    "description": "Is in Churn Suppression Campaign",
    "successLogLabel": "In Churn Campaign",
    "failureLogLabel": "Not in Churn Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "2.0.9",
    "suppressionId": 1947244,
    "micro": 9,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 35,
    "priorityOrder": 2,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },{
    "updatable": true,
    "deletable": false,
    "archivable": false,
    "versionable": true,
    "copyable": true,
    "publishable": true,
    "renamable": true,
    "availableInLibrary": true,
    "unarchivable": false,
    "id": "SR845018BF038DF598012",
    "name": "OPEN_CHURN_CAMPAIGN",
    "description": "Is in Churn Suppression Campaign",
    "successLogLabel": "In Churn Campaign",
    "failureLogLabel": "Not in Churn Campaign",
    "version": 1.000,
    "status": "PUBLISHED",
    "environment": "IN_PRODUCTION",
    "suppressionVersion": "2.0.9",
    "suppressionId": 1947244,
    "micro": 9,
    "errMsg": null,
    "userFriendlyExpression": null,
    "presentationOrder": 35,
    "priorityOrder": 2,
    "alerts": [
      null
    ],
    "state": "RUNNING"
  },
];
export const LIST_OF_VALUE = [
  {
    "id": "SR845018BF038DF598012",
    "name": "NO_EMAIL_CONSENT_P",
    "description": "Have not provided marketing consent via Email",
  },
  {
    "id": "SR842918C61A8C2833661",
    "name": "T",
    "description": "the second",
  },
  {
    "id": "SR4894191022F96805625",
    "name": "SSS",
    "description": "ss",
  },
  {
    "id": "SR8858189237E39544807",
    "name": "OPEN_HYBRID_CAMPAIGN",
    "description": "Is in Hybrid Campaign"
  },
  {
    "id": "SR4551898C3911FD719",
    "name": "TEST_AG_SUPP",
    "description": "TEST_AG_SUPP"
  },
  {
    "id": "SR361018D0238D9A66410",
    "name": "OPEN_RELOAD_CAMPAIGN",
    "description": "Is in Reload Campaign"
  }
]
